### PR TITLE
Feature/add unit tests

### PR DESCRIPTION
**Pull request by prjseal**
Added a unit test project with a couple of test for the if tag helper.
Also add a test site to try the tag helpers out and be able to debug
Added a solution file to house all of the projects and make debugging tests easier.

### CODE REVIEW

**Comment by warrenbuckley** [comment]
@prjseal Can we break this PR up into smaller chunks please, makes it a little easier to test & review IMO
We can add the SLN and test project in another PR

**Comment by prjseal** [comment]
Hi Warren, so would you like me to just add the Our.Umbraco.TagHelpers.Tests project in this PR? And put the other stuff in a separate PR?

**Comment by warrenbuckley** [comment]
@prjseal For now lets just focus on the tests for now as I am not sure a whole starter kit is necessary.

**Comment by prjseal** [comment]
Deleted solution file and test site, just left in the test project

Run the tests by navigating to the test project folder and running `dotnet test`

**Comment by warrenbuckley** [comment]
Looks good to me !
Cheers @prjseal

**Pull request merged**
